### ISSUE TITLE
Save picture to app storage instead of compressing and passing the byte array.

### ISSUE THREAD

**Issue by brfrs** [comp-sci-squad/url-irl#11]
This would maintain picture quality without running into parcel-size limitation.

**Comment by HBBrennan** [comment]
Picture quality is currently fine. Compresses quickly. Writing to disk will take forever. Would the MainActivity wait to save the picture until it starts the List Urls activity? Or would a service tell it when it can load the thumbnail.

**Comment by brfrs** [comment]
I didn't realize that compression was meerly foe display purposes, and that it occured before ocr. Nvm.
