### ISSUE TITLE
Add back button and set launch mode for each activity

### ISSUE THREAD

**Issue by HBBrennan** [comp-sci-squad/url-irl#35]

**Comment by HBBrennan** [comment]
I'm not sure how we wanna bounce between activities once we add history. I'm thinking only one instance of the camera activity should exist. I was thinking we should add a floating action button to all other activities to go back to camera mode.

**Comment by brfrs** [comment]
[this](https://stackoverflow.com/questions/18049284/how-to-go-to-an-already-existing-activity-from-a-different-one) seems relevant

**Comment by HBBrennan** [comment]
https://stackoverflow.com/questions/27230827/back-button-using-getsupportactionbar-and-appcompat-v7-toolbar
