### ISSUE TITLE
App crashes on Samsung Galaxy Note 5 on Camera Closing

### ISSUE THREAD

**Issue by HBBrennan** [comp-sci-squad/url-irl#8]
![image](https://user-images.githubusercontent.com/16947100/29243842-07477aa2-7f5e-11e7-96e0-668164619ddf.png)

![image](https://user-images.githubusercontent.com/16947100/29243839-fe7a83ba-7f5d-11e7-8e59-79efbef52c7f.png)

Possibly add loggin to onPause, etc

**Comment by HBBrennan** [comment]
Also crashes on samsung galaxy s6

**Comment by hummuswins** [comment]
I can't seem to reproduce the issue with my Galaxy S7 Edge

**Comment by brfrs** [comment]
It seems to be a problem with phones that don't implement the camera2 api fully, as the cameraview seems to detect features based only on api level.
